### ISSUE TITLE
Enter UTM manually button not working

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3434] opened 2024-08-20 23:08 UTC
after entering utm zone, easting, and northing nothing happens
![image](https://github.com/user-attachments/assets/4cba5682-1b3c-43f8-a166-bd4295a77caa)

**Comment by LocalNewsTV** [comment] 2024-08-20 23:24
Duplicate of #3428

**Closed as completed by LocalNewsTV** 2024-08-20 23:24 UTC
Labels: duplicate
