### ISSUE TITLE
Edit to the buffer width function when adding a linear observation or treatment for all forms

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1085] opened 2021-09-20 17:33 UTC
When a user chooses to add a "LINE" geometry for their form (aka linear observation or treatment), they are currently asked for a buffer width at every new point while creating a line.

- [x] change this so that the user finishes drawing the line first, with any number of points, and then they are only asked ONCE for a buffer width, so that the entire line is the same buffer width.

**Comment by micheal-w-wells** [comment] 2021-10-25 19:04
I'm not seeing the behaviour described - I reached out to @bburciaga to see if he fixed it already.

When i originally made this (when it was leaflet and not react-leaflet), the behaviour was to prompt once when the line was done.

**Comment by micheal-w-wells** [comment] 2021-10-25 19:28
Few of us tried now - the desired behaviour described above seems to be how it works.

I think either it was temporarily broken, or perhaps the user didn't understand that the line is 'done' when you click the last point, which cues the prompt.

**Comment by bburciaga** [comment] 2021-10-25 20:18
I tested on mobile and found that the bug is at least happening to ios, but not web

**Comment by micheal-w-wells** [comment] 2021-10-26 21:41
@bburciaga and I figured out that the issue is with the leaflet draw plugin not handling events the same on touch devices.  Fixing their code is out of scope so what we are going to do (or @bburciaga is, rather) is going to make a new button that someone can hit after the fact to buffer the shape.

**Closed as completed** 2021-10-28 20:46 UTC
Labels: Mobile
