### ISSUE TITLE
Just dont boot when offline, or intermittent service

### ISSUE THREAD

**Issue by CrystalChadburn** [bcgov/invasivesbc#1471] opened 2022-01-10 23:00 UTC
Offline tokens can't be turned on until March in SSO.  Having them will prevent the user from being kicked off mid-offline session.  Need a best intermediate solution for now.

Access tokens can have an arbitrary end date.

**Comment by micheal-w-wells** [comment] 2022-03-21 15:41
duplicate of robs ticket

**Closed as completed by micheal-w-wells** 2022-03-21 15:41 UTC
